### ISSUE TITLE
Comments in views

### ISSUE THREAD

**Issue by Quantropolis** [Quantropolis/pizzaWiki#2]
Comments in views are all in ruby format, but all need changed to html format so they are actual comments

**Comment by dhintz89** [comment]
Hi there, I'm looking for some simple open-source projects right now to understand the process better.  I can go through and convert those comments for you as a pull request if you'd like.

**Comment by Quantropolis** [comment]
That's not a problem, I was just finishing up for the day and I will sort them out tomorrow morning/ one of the other members will do it overnight; just so you know this project is not/will never be in a public release state, and so may feature multiple cases of bad security/bad practice

**Comment by dhintz89** [comment]
Ok gotcha. Well that's probably even better then for my purposes then.  I'll go ahead and submit a PR then, but certainly feel free to ignore it if you'd prefer.

**Comment by Quantropolis** [comment]
Fixed in push
